<?php

namespace App\Jobs;

use App\Models\SongRequest;
use Google_Client;
use Google_Service_YouTube;

class UploadToYouTubeJob implements ShouldQueue
{
    protected $songRequest;

    public function __construct(SongRequest $songRequest)
    {
        $this->songRequest = $songRequest;
    }

    public function handle()
    {
        $client = new Google_Client();
        $client->setAuthConfig(config('google.client_credentials'));
        $youtube = new Google_Service_YouTube($client);

        $videoPath = storage_path('app/public/song.mp4');
        $videoTitle = 'Generated Song';
        $videoDescription = 'A song generated by ChatGPT and Mureka API.';

        $video = new \Google_Service_YouTube_Video();
        $video->setSnippet(new \Google_Service_YouTube_VideoSnippet([
            'title' => $videoTitle,
            'description' => $videoDescription,
        ]));
        $video->setStatus(new \Google_Service_YouTube_VideoStatus([
            'privacyStatus' => 'public',
        ]));

        $youtube->videos->insert('snippet,status', $video, [
            'data' => file_get_contents($videoPath),
            'mimeType' => 'video/mp4',
            'uploadType' => 'multipart',
        ]);
    }
}
